// Auth Action Constants
export const ADMIN_CONSTANTS = {
  DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
  DASHBOARD_SUCCESS: 'DASHBOARD_SUCCESS',
  DASHBOARD_FAILURE: 'DASHBOARD_FAILURE',

  CREATE_MERCH_REQUEST: 'CREATE_MERCH_REQUEST',
  CREATE_MERCH_SUCCESS: 'CREATE_MERCH_SUCCESS',
  CREATE_MERCH_FAILURE: 'CREATE_MERCH_FAILURE',

  GET_MERCHS_REQUEST: 'GET_MERCHS_REQUEST',
  GET_MERCHS_SUCCESS: 'GET_MERCHS_SUCCESS',
  GET_MERCHS_FAILURE: 'GET_MERCHS_FAILURE',

  DELETE_MERCH_REQUEST: 'DELETE_MERCH_REQUEST',
  DELETE_MERCH_SUCCESS: 'DELETE_MERCH_SUCCESS',
  DELETE_MERCH_FAILURE: 'DELETE_MERCH_FAILURE',

  UPDATE_MERCH_REQUEST: 'UPDATE_MERCH_REQUEST',
  UPDATE_MERCH_SUCCESS: 'UPDATE_MERCH_SUCCESS',
  UPDATE_MERCH_FAILURE: 'UPDATE_MERCH_FAILURE',

  CREATE_COMIC_REQUEST: 'CREATE_COMIC_REQUEST',
  CREATE_COMIC_SUCCESS: 'CREATE_COMIC_SUCCESS',
  CREATE_COMIC_FAILURE: 'CREATE_COMIC_FAILURE',

  GET_COMICS_REQUEST: 'GET_COMICS_REQUEST',
  GET_COMICS_SUCCESS: 'GET_COMICS_SUCCESS',
  GET_COMICS_FAILURE: 'GET_COMICS_FAILURE',

  DELETE_COMIC_REQUEST: 'DELETE_COMIC_REQUEST',
  DELETE_COMIC_SUCCESS: 'DELETE_COMIC_SUCCESS',
  DELETE_COMIC_FAILURE: 'DELETE_COMIC_FAILURE',

  UPDATE_COMIC_REQUEST: 'UPDATE_COMIC_REQUEST',
  UPDATE_COMIC_SUCCESS: 'UPDATE_COMIC_SUCCESS',
  UPDATE_COMIC_FAILURE: 'UPDATE_COMIC_FAILURE',
};