// Auth Action Constants
export const ADMIN_CONSTANTS = {
  DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
  DASHBOARD_SUCCESS: 'DASHBOARD_SUCCESS',
  DASHBOARD_FAILURE: 'DASHBOARD_FAILURE',

  CREATE_MERCH_REQUEST: 'CREATE_MERCH_REQUEST',
  CREATE_MERCH_SUCCESS: 'CREATE_MERCH_SUCCESS',
  CREATE_MERCH_FAILURE: 'CREATE_MERCH_FAILURE',

  GET_MERCHS_REQUEST: 'GET_MERCHS_REQUEST',
  GET_MERCHS_SUCCESS: 'GET_MERCHS_SUCCESS',
  GET_MERCHS_FAILURE: 'GET_MERCHS_FAILURE',

  DELETE_MERCH_REQUEST: 'DELETE_MERCH_REQUEST',
  DELETE_MERCH_SUCCESS: 'DELETE_MERCH_SUCCESS',
  DELETE_MERCH_FAILURE: 'DELETE_MERCH_FAILURE',
};