// Auth Action Constants
export const ADMIN_CONSTANTS = {
  DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
  DASHBOARD_SUCCESS: 'DASHBOARD_SUCCESS',
  DASHBOARD_FAILURE: 'DASHBOARD_FAILURE',

  GET_BEATS_REQUEST: 'GET_BEATS_REQUEST',
  GET_BEATS_SUCCESS: 'GET_BEATS_SUCCESS',
  GET_BEATS_FAILURE: 'GET_BEATS_FAILURE',

  GET_BEAT_BY_ID_REQUEST: 'GET_BEAT_BY_ID_REQUEST',
  GET_BEAT_BY_ID_SUCCESS: 'GET_BEAT_BY_ID_SUCCESS',
  GET_BEAT_BY_ID_FAILURE: 'GET_BEAT_BY_ID_FAILURE',

  CREATE_BEAT_REQUEST: 'CREATE_BEAT_REQUEST',
  CREATE_BEAT_SUCCESS: 'CREATE_BEAT_SUCCESS',
  CREATE_BEAT_FAILURE: 'CREATE_BEAT_FAILURE',
};