// Auth Action Constants
export const AUTH_CONSTANTS = {
  // Me Actions
  ME_REQUEST: 'ME_REQUEST',
  ME_SUCCESS: 'ME_SUCCESS',
  ME_FAILURE: 'ME_FAILURE',
  
  // Login Actions
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  
  // Logout Actions
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  
  // Token Actions
  SET_TOKEN: 'SET_TOKEN',
  CLEAR_TOKEN: 'CLEAR_TOKEN',
  
  // User Actions
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',
  
  // Auth Check
  CHECK_AUTH_REQUEST: 'CHECK_AUTH_REQUEST',
  CHECK_AUTH_SUCCESS: 'CHECK_AUTH_SUCCESS',
  CHECK_AUTH_FAILURE: 'CHECK_AUTH_FAILURE',
};

